### ISSUE TITLE
most_similar method doesn't support 2 or more words

### ISSUE THREAD

**Issue by zppinto** [RaRe-Technologies/w2v_server_googlenews#3]
When trying to query for more than word using "most_similar", the server doesn't return any results. Original word2vec has this capability, and it will be helpful if there is any method/approach that allows it.
@piskvorky do you think it's possible to do it? And how can I do it?
Example: "Harry Potter", "iPhone 5", etc.
Thank you in advance.

**Comment by piskvorky** [comment]
Word2vec is a technique that works over words (both original C and in gensim). It doesn't support multiple words.

There are various hacks to handle sequences of words, such as averaging the embeddings of multiple words (which is already supported by `most_similar`, so not sure what you're asking).

If you mean collocations, that's a preprocessing step independent of word2vec. See the word2vec paper for one possible collocation algorithm (which is also implemented in gensim).

**Comment by zppinto** [comment]
I already find a way by "hacking" your code :)
I should have removed this issue... Sorry!
