### ISSUE TITLE
online demo not working

### ISSUE THREAD

**Issue by eyaler** [RaRe-Technologies/w2v_server_googlenews#7]
the online bonus app not working for me in latest firefox or chrome (with disabled ad blockers and tracking protection)

**Comment by piskvorky** [comment]
Hi, yes, I think we discontinued the "bonus app" server around 4 years ago, sorry. It had been running for 4 years by that point and w2v was already old news by then.

Feel free to run the server yourself – its full source code is in this repo.

**Comment by eyaler** [comment]
it was useful for demonstrating to student. anyway, you might want to put some message that it is offline of hide the gui.
